### ISSUE TITLE
UI Input Validation for Mod Creation & Export Tools

### ISSUE THREAD

**Issue by NightPotato** [NightPotato/Starground-SDK#6]
**Is your feature request related to a problem? Please describe.**
Currently no validation for the information on Create Mod Tool. 

**Describe the solution you'd like**
Implement some validation logic the the data for starting the Mod Creation logic. Check if the `mod_id` is not invalid or null. Same for the other properties within the UI.

**Comment by NightPotato** [comment]
@mbgv When you get to this could you also look into setting the values to the ones store within `SDKData.editorSettings` which contains

![](https://i.imgur.com/bR158p8.png)

**Comment by mbgv** [comment]
Are the export settings global or per mod? From what I can see they seem global, which is not a problem for the game path, but can be for the normal export path

**Comment by NightPotato** [comment]
The `export_path` would be global as its just the output of the packing. This is the path in which the packaged `mod.zip` will end up. I do not see a reason to make each mod have different `export_path` at this time since only content being exported is the `.zip` unless you can give a valid usage in which this method wont work.

**Comment by mbgv** [comment]
I was asking, not because it wouldn't work but because people might like to export different mods to different directories. Still, this is just a minor convenience thing and I don't think its worth to implement right now.
